PROCSERV_VERSION = cd68a34da12ec156c4126932b62947ee195b6210
PROCSERV_SITE = $(call github,ralphlange,procServ,$(PROCSERV_VERSION))
PROCSERV_LICENSE = GPL-3.0
PROCSERV_LICENSE_FILES = COPYING
PROCSERV_AUTORECONF = YES
PROCSERV_CONF_OPTS = --disable-doc
PROCSERV_DEPENDENCIES =

$(eval $(autotools-package))
